#!/usr/bin/env node
/**
 * MySQL RA-TLS Client
 * 
 * This script connects to a MySQL server using SSL/TLS with RA-TLS certificates.
 * It runs inside a Gramine SGX enclave with RA-TLS injected via LD_PRELOAD.
 * 
 * The C launcher (mysql_client_ratls_launcher) handles:
 * - Reading whitelist from smart contract
 * - Setting up environment variables
 * - Setting LD_PRELOAD for RA-TLS injection
 * - Executing this script via execve()
 * 
 * This script only handles MySQL connection and query logic.
 */

const mysql = require('mysql2/promise');
const fs = require('fs');
const readline = require('readline');

/* Configuration constants */
const DEFAULT_CERT_PATH = '/var/lib/mysql-client-ssl/client-cert.pem';
const DEFAULT_KEY_PATH = '/app/wallet/mysql-client-keys/client-key.pem';
const DEFAULT_MYSQL_HOST = 'localhost';
const DEFAULT_MYSQL_PORT = 3306;
const DEFAULT_MYSQL_USER = 'app';  /* Match mysql-ratls server's certificate-authenticated user */

/**
 * Wait for certificate file to be generated by RA-TLS library
 */
async function waitForCertificate(certPath, keyPath, timeoutMs = 30000) {
    const startTime = Date.now();
    const checkInterval = 500;

    console.log('[Client] Waiting for RA-TLS certificates to be generated...');

    while (Date.now() - startTime < timeoutMs) {
        try {
            if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
                const certStat = fs.statSync(certPath);
                const keyStat = fs.statSync(keyPath);
                if (certStat.size > 0 && keyStat.size > 0) {
                    console.log(`[Client] Certificates found: ${certPath}, ${keyPath}`);
                    return true;
                }
            }
        } catch (e) {
            // File might not exist yet, continue waiting
        }
        await new Promise(resolve => setTimeout(resolve, checkInterval));
    }

    return false;
}

/**
 * Connect to MySQL server with RA-TLS
 */
async function connectToMySQL(config) {
    const {
        host,
        port,
        user,
        database,
        certPath,
        keyPath
    } = config;

    console.log(`[Client] Connecting to MySQL server at ${host}:${port}`);

    // Wait for certificates to be generated by RA-TLS library
    const certsReady = await waitForCertificate(certPath, keyPath);
    if (!certsReady) {
        throw new Error('Timeout waiting for RA-TLS certificates');
    }

    // Read certificates
    const cert = fs.readFileSync(certPath);
    const key = fs.readFileSync(keyPath);

    // Create connection with SSL
    const connection = await mysql.createConnection({
        host,
        port,
        user,
        database,
        ssl: {
            cert,
            key,
            rejectUnauthorized: false, // RA-TLS handles verification via SGX attestation,
        },
        connectTimeout: 30000
    });

    console.log('[Client] Connected to MySQL server successfully');
    return connection;
}

/**
 * Execute a single query and print results
 */
async function executeQuery(connection, query) {
    console.log(`[Client] Executing query: ${query}`);
    const [rows] = await connection.execute(query);
    
    if (Array.isArray(rows)) {
        if (rows.length === 0) {
            console.log('[Client] Query returned no rows');
        } else {
            console.log('[Client] Query result:');
            console.table(rows);
        }
    } else {
        console.log(`[Client] Query OK, affected rows: ${rows.affectedRows}`);
    }
    
    return rows;
}

/**
 * Interactive mode - read queries from stdin
 */
async function interactiveMode(connection) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        prompt: 'mysql> '
    });

    console.log('[Client] Entering interactive mode. Type "exit" or "quit" to exit.');
    rl.prompt();

    rl.on('line', async (line) => {
        const query = line.trim();
        
        if (query.toLowerCase() === 'exit' || query.toLowerCase() === 'quit') {
            console.log('[Client] Goodbye!');
            await connection.end();
            process.exit(0);
        }

        if (query) {
            try {
                const [rows] = await connection.execute(query);
                if (Array.isArray(rows)) {
                    if (rows.length === 0) {
                        console.log('Empty set');
                    } else {
                        console.table(rows);
                    }
                } else {
                    console.log(`Query OK, ${rows.affectedRows} row(s) affected`);
                }
            } catch (error) {
                console.error(`Error: ${error.message}`);
            }
        }

        rl.prompt();
    });

    rl.on('close', async () => {
        console.log('\n[Client] Connection closed.');
        await connection.end();
        process.exit(0);
    });

    // Keep the process running
    await new Promise(() => {});
}

/**
 * Main entry point
 */
async function main() {
    console.log('[Client] MySQL RA-TLS Client starting...');

    // Get configuration from environment variables
    const mysqlHost = process.env.MYSQL_HOST || DEFAULT_MYSQL_HOST;
    const mysqlPort = parseInt(process.env.MYSQL_PORT || DEFAULT_MYSQL_PORT, 10);
    const mysqlUser = process.env.MYSQL_USER || DEFAULT_MYSQL_USER;
    const mysqlDatabase = process.env.MYSQL_DATABASE;
    const certPath = process.env.RATLS_CERT_PATH || DEFAULT_CERT_PATH;
    const keyPath = process.env.RATLS_KEY_PATH || DEFAULT_KEY_PATH;
    const query = process.env.MYSQL_QUERY;
    const interactive = process.env.MYSQL_INTERACTIVE === '1';

    // Log configuration
    console.log('[Client] Configuration:');
    console.log(`[Client]   - MySQL Host: ${mysqlHost}`);
    console.log(`[Client]   - MySQL Port: ${mysqlPort}`);
    console.log(`[Client]   - MySQL User: ${mysqlUser}`);
    console.log(`[Client]   - MySQL Database: ${mysqlDatabase || '(none)'}`);
    console.log(`[Client]   - Certificate Path: ${certPath}`);
    console.log(`[Client]   - Key Path: ${keyPath}`);
    console.log(`[Client]   - Interactive Mode: ${interactive}`);

    try {
        // Connect to MySQL
        const connection = await connectToMySQL({
            host: mysqlHost,
            port: mysqlPort,
            user: mysqlUser,
            database: mysqlDatabase,
            certPath,
            keyPath
        });

        if (interactive) {
            // Enter interactive mode
            await interactiveMode(connection);
        } else if (query) {
            // Execute single query
            await executeQuery(connection, query);
            await connection.end();
            console.log('[Client] Client finished');
        } else {
            // No query and not interactive, just verify connection and exit
            console.log('[Client] Connection verified successfully');
            await connection.end();
            console.log('[Client] Client finished');
        }
    } catch (error) {
        console.error(`[Client] Error: ${error.message}`);
        process.exit(1);
    }
}

// Run main
main().catch(error => {
    console.error(`[Client] Fatal error: ${error.message}`);
    process.exit(1);
});
